paths:
  raw_dtseries_dir: /home/mirex/Science/hcp_subjects/
  atlas_dlabel: data/atlas/300Parcels_Yeo2011_7Networks.dlabel.nii
  ptseries_dir: data/derivatives/ptseries
  hmm_dir: data/derivatives/hmm
  betas_dir: data/derivatives/hmm/betas
  parcel_labels_dlabel: data/atlas/300Parcels_Yeo2011_7Networks.dlabel.nii
  subjects_csv: data/subjects_info.csv
  # Optional volumetric labels NIfTI with integer codes 1..P matching parcel order
  # parcel_labels_nii: data/atlas/Yeo300_2mm_parcels.nii.gz
  #ToDo remove?
  surface_dir: data/atlas/fsLR_32k_surfaces

logging:
  format: plain          # json | plain
  level: INFO            # DEBUG | INFO | WARNING | ERROR

hmm:
  K: 4
  backend: arhmm # arhmm | slds
  ar_order: 1 # AR lag order for ARHMM
  slds_latent_dim: 4 # latent dimension for SLDS (when enabled)
  max_iter: 10
  seed: 42
  tr_sec: 0.72

parcellate:
  method: MEAN 
  suffix: Yeo300

stats:
  n_perm_rm: 100        # permutations for repeated-measures state stats
  n_perm_between: 100   # permutations for global between-subject stats

group_design:
  contrast: sex          # sex, or intercept
  demean: ["fd"]         # frame displacement, i.e. head motion
  include_fd: true

palm:
  enabled: true         # set true to run PALM at the end
  n_perm: 5000
  two_tailed: true
  tfce: false 
  tfce2D: false          # enable for surface/2D TFCE if applicable
  cifti: true            # requires PALM with CIFTI support
  palm_bin: palm         # path or name of the PALM binary
  ise: true #  Keep ise: true for one-sample (intercept) tests. If you later switch to a between-group contrast (e.g., sex), turn ise off (permutations are appropriate there).
  use_zscored: false

evaluation:
  enabled: true
  # Candidate K values for the sweep (omit to use hmm.K)
  K_values: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  # Repeat fits across multiple seeds to assess stability (omit to use hmm.seed)
  seeds: [19, 5, 91, 63, 81, 51, 3, 99, 18, 47]
  # Optional explicit output directory (defaults to <paths.hmm_dir>/model_selection)
  # out_dir: data/derivatives/hmm/model_selection

  # Stage 1: Junk-state detectors (heuristic thresholds)
  junk:
    fo_median_min: 0.01
    dt_mean_min_tr: 2.0
    presence_min: 0.5

  # Stage 3: Indecision detectors (posterior probabilities)
  indecision:
    dominance_thr: 0.8
    ambiguous_thr: 0.5

  # Stage 4: Clone detectors (state mean-pattern similarity)
  clone:
    corr_thr: 0.9

  # Stage 5: Reality check (split merged 4800TR into 4×1200TR)
  reliability:
    run_len_tr: 1200
    n_runs: 4
